### PR TITLE
[Review] Improved Styling

### PR DESCRIPTION
**Pull request by dfosco**
- [x] Import theme styles
 - [x] Refactor CSS

### CODE REVIEW

**Comment by dfosco** [comment]
@tamorim @amoreira Please review

**Comment by tamorim** [comment]
image

@dfosco I really think it needs more work before merging...

**Comment by dfosco** [comment]
@tamorim This is my current version  I did some theme changes in the branch `feature/responsive-category-page` that export styles being used by the Navigation Menu.

However, it should look better _by default_, no matter the theme in use... I'll improve it this week so we can close this PR 
image

**Comment by dfosco** [comment]
@tamorim Try now, fallback styles should be in place:

image

**Comment by dfosco** [comment]
@tamorim hey bro, can you close this? thanks bro.

**Pull request merged**
